package co.edu.uniquindio.poo.viewController;

import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.ListView;

public class HomeClienteViewController {

    @FXML
    private Button btnVerDetalles;

    @FXML
    private Button btnCerrarSesion;

    @FXML
    private Label lblTitulo;

    @FXML
    private ListView<?> listVehiculos;

    @FXML
    void onCerrarSesion(ActionEvent event) {

    }

    @FXML
    void onVerDetalles(ActionEvent event) {

    }

}
